package vcodeapi

var categoryMap = map[string]string{
	"-1": "Other",
	"1": "Directory Traversal",
	"2": "Untrusted Search Path",
	"3": "Buffer Overflow",
	"4": "Buffer Management Errors",
	"5": "Format String",
	"6": "Numeric Errors",
	"7": "API Abuse",
	"8": "Information Leakage",
	"9": "Dangerous Functions",
	"10": "Credentials Management",
	"11": "Authentication Issues",
	"12": "Cryptographic Issues",
	"13": "Race Conditions",
	"14": "Time and State",
	"15": "Session Fixation",
	"16": "Error Handling",
	"17": "Code Quality",
	"18": "OS Command Injection",
	"19": "SQL Injection",
	"20": "Cross-Site Scripting",
	"21": "CRLF Injection",
	"22": "Encapsulation",
	"24": "Untrusted Initialization",
	"25": "Insufficient Input Validation",
	"26": "Deployment Configuration",
	"27": "Server Configuration",
	"28": "Code Injection",
	"29": "Authorization Issues",
	"30": "Potential Backdoor",
	"31": "Coding Standards",
	"32": "Insecure Dependencies",
}